sudo: required
servised: 
  - docker

 before_install:
  -  docker build -t katerynaShtets/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true katerynaShtets/docker-react npm run test
  